openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: '{SERVER_URL}'
    variables:
      SERVER_URL:
        description: Environment - staging or production
        default: http://127.0.0.1:2001
        enum:
          - http://127.0.0.1:2001
          - http://5.35.101.236
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /askGpt:
    post:
      description: "Ask GPT"
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              Example#1:
                value: "Какой язык программирования самый лучший?"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Python"

  /savwAnswer:
    post:
      description: "Save answer"
      requestBody:
        content:
          application/json:
            schema:
              type: {
                "firstName": "John",
                "lastName": "Doe",
                "telegramId": 123456789,
                "isBot": false,
                "question": "What is your favorite color?"
              }
            examples:
              Example#1:
                value: "Какой язык программирования самый лучший?"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Python"
components:
  schemas: {}