ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 3000
    environment:
        db_name: $DB_NAME
        db_password: $DB_PASSWORD
        db_url: $DB_URL

