ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 2001
    environment:
        db_name: $DB_NAME
        db_password: $DB_PASSWORD
        db_url: $DB_URL
        yandex_iam_token: $IAM_TOKEN
        yandex_folder_id: $FOLDER_ID
        server_url: $SERVER_URL
    security:
        ssl:
            keyStore: keystore.jks
            keyAlias: $KEY_ALIAS
            keyStorePassword: $KEYSTORE_PASSWORD
            privateKeyPassword: $KEY_PASSWORD


